force-app/main/default/objects/Quote/fields/Sales_Tax__c.field-meta.xml
<CustomField>
    <fullName>Sales_Tax__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Tax</label>
    <referenceTo>Sales_Tax__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Tax__c/Sales_Tax__c.object-meta.xml
<CustomObject>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Sales Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Tax__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sales_Tax__c/fields/Sales_Tax__c.field-meta.xml
<CustomField>
    <fullName>Sales_Tax__c</fullName>
    <label>Sales Tax</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Tax__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandler.cls
public class QuoteTriggerHandler {
    public static void changeSalesTaxLookup(List<Quote> quoteList,Map<Id,Quote> oldMap){
        Set<String> state = new Set<String>();
        Set<String> city = new Set<String>();
        
        for(Quote quote : quoteList){
            if(quote.BillingState != null ||(oldMap != null && quote.BillingState != oldMap.get(quote.Id).BillingState)){
                state.add(quote.BillingState);
            }
            if(quote.BillingCity != null || (oldMap != null && quote.BillingCity != oldMap.get(quote.Id).BillingCity)){
                city.add(quote.BillingCity);
            }
        }
        
        Map<String,Id> salesTaxMap = new Map <String,Id>();
        for(Sales_Tax__c  sales : [SELECT Id,State__c,City__c FROM Sales_Tax__c WHERE State__c IN: state AND City__c IN: city ] ){
            salesTaxMap.put(sales.State__c + ' |'+ sales.City__c, sales.Id);
        }
        
        for(Quote quote : quoteList){
            if(salesTaxMap.containsKey(quote.BillingState + ' |' + quote.BillingCity)){ 
                quote.Sales_Tax__c = salesTaxMap.get(quote.BillingState + ' |' + quote.BillingCity); 
            }
            else{
                quote.Sales_Tax__c = null;
            }
        }
    }  
}