force-app/main/default/objects/Batch_Summary__c/Batch_Summary__c.object-meta.xml
<CustomObject>
    <label>Batch Summary</label>
    <nameField>
        <label>Batch Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Summary__c/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <label>Job Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InactiveCustomerCleanupScheduler.cls
public class InactiveCustomerCleanupScheduler implements Schedulable{
    
    public void execute(SchedulableContext sc){
        List<Batch_Summary__c> batchJob = [SELECT Job_Name__c, Status__c, Batch_Run_Date__c FROM Batch_Summary__c WHERE Job_Name__c = 'Inactive Customer Clean Up Batch' AND Batch_Run_Date__c =: System.Today()];
        if(batchJob.isEmpty()){
            Batch_Summary__c batchData = new Batch_Summary__c(Job_Name__c = 'Inactive Customer Clean Up Batch',Batch_Run_Date__c = System.today(),Status__c = 'Started');
            insert batchData;
            Database.executeBatch(new InactiveCustomerCleanupBatch(batchData.Id), 200);
        }
    }
}