force-app/main/default/objects/Account/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <label>Engagement Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Score_History__c/Score_History__c.object-meta.xml
<CustomObject>
    <label>Score History</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Score History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Score_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Score History</relationshipLabel>
    <relationshipName>Score_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Score_History__c/fields/New_Score__c.field-meta.xml
<CustomField>
    <fullName>New_Score__c</fullName>
    <label>New Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Score_History__c/fields/Old_Score__c.field-meta.xml
<CustomField>
    <fullName>Old_Score__c</fullName>
    <label>Old Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomerEngagementScoringQueueable.cls
public class CustomerEngagementScoringQueueable implements Queueable{
    Set<Id> accId = new Set<Id>();
    public CustomerEngagementScoringQueueable(Set<Id> accId){
        this.accId = accId;
    }
    
    public void execute(QueueableContext context){
        List<Account> account = [SELECT Id, Engagement__c,(SELECT Id FROM Cases WHERE Status != 'Closed'),(SELECT Id FROM Opportunities WHERE IsWon = true),(SELECT Id FROM Contacts) FROM Account WHERE Id IN :accId];
        List<Account> accountUpdate = new List<Account>();
        List<Score_History__c> historyScore = new List<Score_History__c>();
        
        for(Account acc : account) {
            Integer openCases = acc.Cases.size();
            Integer wonOpps = acc.Opportunities.size();
            Integer activeContacts = acc.Contacts.size();
            Decimal oldScore = (acc.Engagement__c == null) ? 0 : acc.Engagement__c;
            Decimal newScore = (wonOpps * 10) + (activeContacts * 2) - (openCases * 5);
            newScore = Math.max(0, newScore);
            Boolean shouldUpdate = false;
            if(oldScore == 0 && newScore > 0) {
                shouldUpdate = true;
            } 
            else if(oldScore > 0) {
                Decimal changePercentage = Math.abs(newScore - oldScore) / oldScore;
                if (changePercentage > 0.10) {
                    shouldUpdate = true;
                }
            }
            if(shouldUpdate) {
                acc.Engagement__c = newScore;
                accountUpdate.add(acc);
                historyScore.add(new Score_History__c(Account__c = acc.Id,Old_Score__c = oldScore,New_Score__c = newScore));
            }
        }
        if(!accountUpdate.isEmpty()) {
            update accountUpdate;
        }
        if(!historyScore.isEmpty()) {
            insert historyScore;
        }
    }
}