force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact_Update_Log__c/Contact_Update_Log__c.object-meta.xml
<CustomObject>
    <label>Contact Update Log</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Contact Update Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Update Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Update_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Update Log</relationshipLabel>
    <relationshipName>Contact_Update_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Update_Log__c/fields/New_Phone__c.field-meta.xml
<CustomField>
    <fullName>New_Phone__c</fullName>
    <label>New Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact_Update_Log__c/fields/Old_Phone__c.field-meta.xml
<CustomField>
    <fullName>Old_Phone__c</fullName>
    <label>Old Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/ContactFutureClass.cls
public class ContactFutureClass {
    @future
    public static void insertRecordInContact(String updatedData,String oldChangedData){
        Map<Id, Contact> oldRecord = (Map<Id, Contact>)JSON.deserialize(oldChangedData,Map<Id, Contact>.class);
        List<Contact> conList = (List<Contact>)JSON.deserialize(updatedData,List<Contact>.class);
        
        List<Contact_Update_Log__c> conLogList = new List<Contact_Update_Log__c>();
        for(Contact con : conList){
            if(con.Email != oldRecord.get(con.Id).Email && con.Phone != oldRecord.get(con.Id).Phone){
                conLogList.add(new Contact_Update_Log__c(Contact__c = con.Id, Old_Email__c = oldRecord.get(con.Id).Email, New_Email__c = con.Email, Old_Phone__c = oldRecord.get(con.Id).Phone, New_Phone__c = con.Phone));
            }
            
            else if(con.Email != oldRecord.get(con.Id).Email){
                conLogList.add(new Contact_Update_Log__c(Contact__c = con.Id, Old_Email__c = oldRecord.get(con.Id).Email, New_Email__c = con.Email));
            }
            
            else if(con.Phone != oldRecord.get(con.Id).Phone){
                conLogList.add(new Contact_Update_Log__c(Contact__c = con.Id, Old_Phone__c = oldRecord.get(con.Id).Phone, New_Phone__c = con.Phone));
            }
            
        }
        if(!conLogList.isEmpty()){
        	insert conLogList;   
        }
    }
}